### ISSUE TITLE
VS2015 and win7(64bit) get break image.

### ISSUE THREAD

**Issue by fengguangle** [mofo7777/H264Dxva2Decoder#1]
I have used this project in vs2015 and win7.
And same mp4 file.
Cant get video image correctly.

GPU: Intel graphic HD 510

**Comment by mofo7777** [comment]
I have only tested Intel HD Graphics 4000. I've made an update because this GPU didn't handle DXVAHD_STREAM_STATE_ALPHA_DATA like NVIDIA. Try to change values in CDxva2Decoder::ConfigureVideoProcessor, like i did. Also i see some source code that does special things when GPU is Intel. I'll try to see.

**Comment by mofo7777** [comment]
On windows10 (Intel graphic HD 500), decoding is not good. I will investigate. Perhaps Nalu buffer needs alignment with Intel GPU.

**Comment by mofo7777** [comment]
I found the problem. I don't know if it comes from DXVA2 or Intel graphic HD 500/510.

The problem is the start code from the nalu buffer ; 0x00, 0x00, 0x00, 0x01.

When movie file has nalu lenght size of 4, i simply replace the four bytes with the start code above.

Using this start code 0x00, 0x00, 0x01  permits to play the video file correctly. So it seems that start code  0x00, 0x00, 0x00, 0x01 is not handled.

Here is a quick workaround with the video sample "Beach - 10890.mp4".

` Main.cpp

    if(pVideoBuffer.GetBufferSize() == 0){

        NalUnitBuffer.SetStartPositionAtBeginning();
        IF_FAILED_THROW(NalUnitBuffer.SetStartPosition(1)); // Add this line
        IF_FAILED_THROW(pDxva2Decoder->DecodeFrame(NalUnitBuffer, cH264NaluParser.GetPicture(), llTime, iSubSliceCount));
        IF_FAILED_THROW(pDxva2Decoder->DisplayFrame());
    }`

Off course, for video files with subslices, this workaround will not be enough.

**Comment by mofo7777** [comment]
after talking with Intel, I found that I was not handle dxva2 specifications correctly. Now it's ok with version 1.1.0.0

**Comment by fengguangle** [comment]
ok, thank you mofo.
