### ISSUE TITLE
Dxva2Renderer.cpp - Line: 372 hr = E_NOINTERFACE

### ISSUE THREAD

**Issue by smourier** [mofo7777/H264Dxva2Decoder#3]
Hi,

I get this error when running the program (compiled using any combination of x86/x64/Debug/Release). I also tried multiple mp4 files.

The line is this:

    IF_FAILED_THROW(DXVAHD_CreateDevice(m_pDevice9Ex, &desc, DXVAHD_DEVICE_USAGE_PLAYBACK_NORMAL, NULL, &pDXVAHD));

**Comment by mofo7777** [comment]
Hello.

From the doc : [DXVAHD_CreateDevice](https://docs.microsoft.com/en-us/windows/win32/api/dxvahd/nf-dxvahd-dxvahd_createdevice) : 

E_NOINTERFACE : The Direct3D device does not support DXVA-HD.

It seems your GPU does not support DXVA-HD. A workaround could be to use IDirectXVideoProcessor instead of IDXVAHD_VideoProcessor : 

[DXVA Video Processing](https://docs.microsoft.com/en-us/windows/win32/medfound/dxva-video-processing)


What's your GPU ?

**Comment by smourier** [comment]
Indeed, it's an AMD Radeon RX 5600 XT, it probably doesn't support it.

I guess this it it: https://stackoverflow.com/questions/60567404/video-rendering-on-windows-when-dxva-hd-is-not-available

**Comment by mofo7777** [comment]
Hello.

I've added H264Dxva2DecoderSourceCodeForAtiCard.7z in SourceCodeForAtiCards directory. It is a quick implementation. Could you give me feedback. Thank you.

**Comment by smourier** [comment]
It works fine now.

It's interesting to note (on my PC), it takes around 35% of the GPU while when I use Windows 10's basic "Movies & TV" app, it runs at around 13% GPU (but takes an extra 5% off dwm.exe).

Also, 35% is roughly the same usage as for the old "Windows Media Player" as well as VLC.

**Comment by mofo7777** [comment]
Thank you.

I suppose Windows 10 uses ID3D11VideoDecoder or ID3D12VideoDecoder, instead of IDirectXVideoDecoder.

Here is a way  to improve performance : [direct3d-9ex-improvements](https://docs.microsoft.com/en-us/windows/win32/direct3darticles/direct3d-9ex-improvements).

If GPU only supports DirectX9, perhaps the technic above is used.


Also in Dxva2Renderer.cpp could you replace all :

IF_FAILED_THROW(m_pDevice9Ex->Present(NULL, NULL, NULL, NULL));

with :

IF_FAILED_THROW(m_pDevice9Ex->PresentEx(NULL, NULL, NULL, NULL, 0));

and send me feedback about GPU usage, thank you.
